### ISSUE TITLE
Tasten unter Firefox (41.0) nicht zuweisbar

### ISSUE THREAD

**Issue by memo42** [timroes/quiz#3]
Ging das mal?

**Comment by timroes** [comment]
Ich schaue, dass es ich es unterm Wochenende mal teste. Bin mir nicht sicher, ob ich es jemals unter Firefox getestet hatte oder nur Chrome(ium),

**Comment by memo42** [comment]
Habs gefunden. Firefox hat irgendwie andere Keyevents. Hab nen pull-request gestellt.
